apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events-collector
spec:
  concurrencyPolicy: Forbid
  schedule: "55 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: events-collector
              image: fintlabs.azurecr.io/events-collector:build.3
              envFrom:
                - configMapRef:
                    name: fint-environment
                - secretRef:
                    name: fint-events-collector
              env:
                - {name: fint.audit.baseurl, value: https://beta.felleskomponent.no/events}
                - {name: fint.audit.username, value: pwfatut}
                - {name: fint.audit.password, value: pwfatut}
                - {name: fint.audit.blob.container-name, value: fint-events-beta}
                - {name: fint.audit.orgids, value: fintlabs.no,viken.no}
